# Site settings
title: Start working remotely
email: youremailaddress@gmail.com
description: "You know you want it, but you don't exactly know how to that. Get the first free tip on how to start working from the beach in your inbox."
baseurl: # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url:
github_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
